language: ruby
cache: bundler
rvm:
  - 2.1.1
install: true
env:
  global:
    - CASEWORK_FRONTEND_DOMAIN=lr-casework-frontend.herokuapp.com
    - SEARCH_FRONTEND_DOMAIN=lr-property.herokuapp.com
    - PROPERTY_FRONTEND_DOMAIN=lr-property-frontend.herokuapp.com
    - MINT_API_DOMAIN=lr-mint.herokuapp.com
    - PUBLICTITLE_API_DOMAIN=lr-public-titles-api.herokuapp.com
    - LR_SEARCH_API_DOMAIN="lr-search-api.herokuapp.com"

before_install:
- 'echo ''gem: --no-ri --no-rdoc'' > ~/.gemrc'
before_script:
  - bundle install
script:
  - bundle exec cucumber --tags ~@wip
  - ls
  - curl -X POST -H "Content-Type: application/json" -d @./report.json http://lr-test-dashboard.herokuapp.com/import/cucumber
