language: ruby
rvm:
  - 2.1.1

install: true

before_script:
  - bundle install
  - "export CASEWORK_FRONTEND_URL=http://lr-casework-frontend.herokuapp.com"

script:
  - bundle exec cucumber --tags ~@wip
